### ISSUE TITLE
Add new Repository https://www.cphub.net

### ISSUE THREAD

**Issue by DKeppi** [szyb/synopackage_dotnet#330] opened 2023-07-12 12:28 UTC
**Repository URL**
https://www.cphub.net

**Are you an owner?**
no

**Is there a website for this repository?**
https://www.cphub.net

**Additional info**
This is a project initiated by users of the German Community (http://www.synology-forum.de/)

**Comment by szyb** [comment] 2023-07-12 13:01
Thank you for posting.
Cphub is already on the list, but marked as inactive source. It is for a reason. This is very unstable source, which is often unavailable (due to internal issue with database connection -  according to the error message). This leads to performance issue in synopackage itself due to exceeding our hosting resources and synopackage is down because of it.

So first I need to fix the problem on synopackage side and handle inactivity of sources in a better way than it is now.
Currently I don't have time for that. Moreover I started new project for synopackage, which should handle this issue by design, but I also have no time for that as well :( I feel bad because of this, but this is how it looks like...

**Comment by szyb** [comment] 2023-07-16 13:24
Cphub is back to active.

I've made some performance enhancement for the repository (which is bottleneck of the whole page) and we will see what happen next :)

**Comment by szyb** [comment] 2023-07-19 20:20
Nope. Fix didn't help when cphub is down. Had to turn it off again :( 

However, the repository can handle more requests than it was before, so it helped somehow. Unfortunately only when all sources are online.

**Comment by szyb** [comment] 2023-11-02 16:59
Closing. IT is on the list since August 2023

**Closed by szyb** 2023-11-02 16:59 UTC
